### CREAR PROVEEDOR
POST http://localhost:3000/api/proveedores
Content-Type: application/json

{
    "nombre": "Representaciones Nataly S.A.C",
    "ruc": "20600007522",
    "direccion": "Av. Aviacion 721",
    "telefono": "4746922",
    "celular": "915115894",
    "correo": "representacionesnataly@gmail.com"
}

### OBTENER TODOS LOS PROVEEDORES
GET http://localhost:3000/api/proveedores

### OBTENER PROVEEDOR POR ID
GET http://localhost:3000/api/proveedores/1

### ACTUALIZAR PROVEEDOR POR ID
PUT http://localhost:3000/api/proveedores/1
Content-Type: application/json

{
    "nombre": "Representaciones Nataly S.A.C actualizado",
    "ruc": "20600007522",
    "direccion": "Av. Aviacion 721",
    "telefono": "4746922",
    "celular": "915115894",
    "correo": "representacionesnataly@gmail.com"
}

### ELIMINAR PROVEEDOR POR ID
DELETE  http://localhost:3000/api/proveedores/1
